# Generated by Django 3.1.14 on 2022-03-30 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('netflix', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
